/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS `rl_experiencias_candidaturas` (
  `es_candidatura` int(10) unsigned NOT NULL,
  `es_experiencia` int(10) unsigned NOT NULL,
  PRIMARY KEY (`es_candidatura`,`es_experiencia`),
  KEY `es_experiencia` (`es_experiencia`),
  CONSTRAINT `rl_experiencias_candidaturas_ibfk_1` FOREIGN KEY (`es_candidatura`) REFERENCES `tb_candidaturas` (`pr_candidatura`),
  CONSTRAINT `rl_experiencias_candidaturas_ibfk_2` FOREIGN KEY (`es_experiencia`) REFERENCES `tb_experiencias` (`pr_experienca`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `rl_formacoes_candidaturas` (
  `es_candidatura` int(10) unsigned NOT NULL,
  `es_formacao` int(10) unsigned NOT NULL,
  PRIMARY KEY (`es_candidatura`,`es_formacao`),
  KEY `es_formacao` (`es_formacao`),
  CONSTRAINT `rl_formacoes_candidaturas_ibfk_1` FOREIGN KEY (`es_candidatura`) REFERENCES `tb_candidaturas` (`pr_candidatura`),
  CONSTRAINT `rl_formacoes_candidaturas_ibfk_2` FOREIGN KEY (`es_formacao`) REFERENCES `tb_formacao` (`pr_formacao`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `rl_gruposvagas_questoes` (
  `es_grupovaga` int(10) unsigned NOT NULL,
  `es_questao` int(10) unsigned NOT NULL,
  `in_ordem` tinyint(3) unsigned NOT NULL,
  PRIMARY KEY (`es_grupovaga`,`es_questao`),
  KEY `es_questao` (`es_questao`),
  CONSTRAINT `rl_gruposvagas_questoes_ibfk_1` FOREIGN KEY (`es_grupovaga`) REFERENCES `tb_gruposvagas` (`pr_grupovaga`),
  CONSTRAINT `rl_gruposvagas_questoes_ibfk_2` FOREIGN KEY (`es_questao`) REFERENCES `tb_questoes` (`pr_questao`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `rl_instituicoes_usuarios` (
  `es_instituicao` int(10) unsigned NOT NULL,
  `es_usuario` int(10) unsigned NOT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`es_instituicao`,`es_usuario`),
  KEY `es_usuario` (`es_usuario`),
  CONSTRAINT `rl_instituicoes_usuarios_ibfk_1` FOREIGN KEY (`es_instituicao`) REFERENCES `tb_instituicoes3` (`pr_instituicao`),
  CONSTRAINT `rl_instituicoes_usuarios_ibfk_2` FOREIGN KEY (`es_usuario`) REFERENCES `tb_usuarios` (`pr_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `rl_questoes_vagas` (
  `es_vaga` int(10) unsigned NOT NULL,
  `es_questao` int(10) unsigned NOT NULL,
  `in_ordem` tinyint(3) unsigned DEFAULT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`es_vaga`,`es_questao`),
  KEY `es_questao` (`es_questao`),
  CONSTRAINT `rl_questoes_vagas_ibfk_1` FOREIGN KEY (`es_vaga`) REFERENCES `tb_vagas` (`pr_vaga`),
  CONSTRAINT `rl_questoes_vagas_ibfk_2` FOREIGN KEY (`es_questao`) REFERENCES `tb_questoes` (`pr_questao`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `rl_vagas_avaliadores` (
  `es_vaga` int(10) unsigned NOT NULL,
  `es_usuario` int(10) unsigned NOT NULL,
  PRIMARY KEY (`es_vaga`,`es_usuario`),
  KEY `es_usuario` (`es_usuario`),
  CONSTRAINT `rl_vagas_avaliadores_ibfk_1` FOREIGN KEY (`es_vaga`) REFERENCES `tb_vagas` (`pr_vaga`),
  CONSTRAINT `rl_vagas_avaliadores_ibfk_2` FOREIGN KEY (`es_usuario`) REFERENCES `tb_usuarios` (`pr_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `tb_anexos` (
  `pr_anexo` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `es_candidatura` int(10) unsigned DEFAULT NULL,
  `es_questao` int(10) unsigned DEFAULT NULL,
  `es_formacao` int(10) unsigned DEFAULT NULL,
  `es_experiencia` int(10) unsigned DEFAULT NULL,
  `in_tipo` tinyint(3) unsigned NOT NULL,
  `vc_mime` varchar(255) COLLATE utf8_bin NOT NULL,
  `vc_arquivo` varchar(255) COLLATE utf8_bin NOT NULL,
  `bi_conteudo` mediumblob,
  `in_tamanho` int(10) unsigned NOT NULL,
  `es_usuarioCadastro` int(10) unsigned NOT NULL,
  `dt_cadastro` datetime NOT NULL,
  `es_usuarioAlteracao` int(10) unsigned DEFAULT NULL,
  `dt_alteracao` datetime DEFAULT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin NOT NULL DEFAULT '0',
  PRIMARY KEY (`pr_anexo`),
  UNIQUE KEY `es_candidatura` (`es_candidatura`,`es_questao`) USING BTREE,
  UNIQUE KEY `es_experiencia` (`es_experiencia`) USING BTREE,
  UNIQUE KEY `es_formacao` (`es_formacao`) USING BTREE,
  KEY `IDCandidatura` (`es_candidatura`),
  KEY `IdUsuarioCadastrador` (`es_usuarioCadastro`),
  KEY `IdUsuarioUltimoAlterador` (`es_usuarioAlteracao`),
  KEY `es_questao` (`es_questao`),
  CONSTRAINT `tb_anexos_ibfk_1` FOREIGN KEY (`es_candidatura`) REFERENCES `tb_candidaturas` (`pr_candidatura`),
  CONSTRAINT `tb_anexos_ibfk_2` FOREIGN KEY (`es_usuarioCadastro`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_anexos_ibfk_3` FOREIGN KEY (`es_usuarioAlteracao`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_anexos_ibfk_5` FOREIGN KEY (`es_experiencia`) REFERENCES `tb_experiencias` (`pr_experienca`)
) ENGINE=InnoDB AUTO_INCREMENT=24035 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_candidatos` (
  `pr_candidato` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `vc_nome` varchar(250) COLLATE utf8_bin NOT NULL,
  `vc_nomesocial` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `ch_cpf` char(14) COLLATE utf8_bin NOT NULL,
  `vc_rg` varchar(15) COLLATE utf8_bin NOT NULL,
  `in_genero` int(10) unsigned NOT NULL,
  `vc_generoOptativo` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `in_raca` int(10) unsigned DEFAULT NULL,
  `vc_orgaoEmissor` varchar(15) COLLATE utf8_bin NOT NULL,
  `vc_email` varchar(250) COLLATE utf8_bin NOT NULL,
  `vc_telefone` varchar(15) COLLATE utf8_bin NOT NULL,
  `vc_telefoneOpcional` varchar(15) COLLATE utf8_bin DEFAULT NULL,
  `vc_linkedin` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `dt_nascimento` date DEFAULT NULL,
  `vc_pais` varchar(150) COLLATE utf8_bin DEFAULT NULL,
  `vc_cidadeEstrangeira` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `vc_logradouro` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `vc_numero` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  `vc_bairro` varchar(150) COLLATE utf8_bin DEFAULT NULL,
  `vc_complemento` varchar(150) COLLATE utf8_bin DEFAULT NULL,
  `vc_cep` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  `es_municipio` bigint(20) DEFAULT NULL,
  `in_nivelAcademico` int(10) unsigned DEFAULT NULL,
  `tx_informacoesAcademicas` mediumtext COLLATE utf8_bin,
  `tx_experienciaSetorPublico` mediumtext COLLATE utf8_bin,
  `tx_experienciasProfissionais` mediumtext COLLATE utf8_bin,
  `tx_atividadesVoluntarias` mediumtext COLLATE utf8_bin,
  `tx_referenciasProfissionais` mediumtext COLLATE utf8_bin,
  `in_exigenciasComuns` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  `bl_sentenciado` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  `bl_processoDisciplinar` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  `bl_ajustamentoFuncionalPorDoenca` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  `bl_elegivel` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  `bl_politicaPrivacidade` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  `es_usuarioCadastro` int(10) unsigned DEFAULT NULL,
  `dt_cadastro` datetime NOT NULL,
  `es_usuarioAlteracao` int(10) unsigned DEFAULT NULL,
  `dt_alteracao` datetime NOT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin NOT NULL DEFAULT '0',
  `bl_aceiteTermo` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  `bl_aceitePrivacidade` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  `bl_brumadinho` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`pr_candidato`),
  KEY `IdMunicipio` (`es_municipio`),
  KEY `IdUsuarioCadastrador` (`es_usuarioCadastro`),
  KEY `IdUsuarioUltimoAlterador` (`es_usuarioAlteracao`),
  CONSTRAINT `tb_candidatos_ibfk_1` FOREIGN KEY (`es_municipio`) REFERENCES `tb_municipios` (`pr_municipio`),
  CONSTRAINT `tb_candidatos_ibfk_2` FOREIGN KEY (`es_usuarioCadastro`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_candidatos_ibfk_3` FOREIGN KEY (`es_usuarioAlteracao`) REFERENCES `tb_usuarios` (`pr_usuario`)
) ENGINE=InnoDB AUTO_INCREMENT=6173 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_candidaturas` (
  `pr_candidatura` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `es_candidato` int(10) unsigned NOT NULL,
  `es_vaga` int(10) unsigned NOT NULL,
  `es_status` tinyint(3) unsigned NOT NULL,
  `dt_cadastro` datetime DEFAULT NULL,
  `dt_realizada` datetime DEFAULT NULL,
  `dt_candidatura` datetime NOT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin NOT NULL DEFAULT '0',
  `vc_urlDocumentoIdentificacao` varchar(500) COLLATE utf8_bin DEFAULT NULL,
  `vc_urlCurriculum` varchar(500) COLLATE utf8_bin DEFAULT NULL,
  `en_aderencia` enum('0','1','2') COLLATE utf8_bin DEFAULT NULL COMMENT '1->teste de aderencia obrigatório, 2-> teste de aderência feito',
  `dt_aderencia` datetime DEFAULT NULL,
  `es_avaliador_competencia1` int(10) unsigned DEFAULT NULL,
  `es_avaliador_especialista` int(10) unsigned DEFAULT NULL,
  `es_avaliador_curriculo` int(10) unsigned DEFAULT NULL,
  `tx_expectativa_momento` text COLLATE utf8_bin,
  `tx_observacoes_momento` text COLLATE utf8_bin,
  `tx_pontos_fortes` text COLLATE utf8_bin,
  `tx_pontos_melhorias` text COLLATE utf8_bin,
  `tx_feedback` text COLLATE utf8_bin,
  `tx_comentarios` text COLLATE utf8_bin,
  `en_hbdi` enum('1','2') COLLATE utf8_bin DEFAULT NULL,
  `dt_hbdi` datetime DEFAULT NULL,
  PRIMARY KEY (`pr_candidatura`),
  UNIQUE KEY `es_candidato` (`es_candidato`,`es_vaga`),
  KEY `IdCandidato` (`es_candidato`),
  KEY `IdVaga` (`es_vaga`),
  KEY `es_status` (`es_status`),
  KEY `es_avaliador_competencia1` (`es_avaliador_competencia1`),
  KEY `es_avaliador_competencia2` (`es_avaliador_especialista`),
  KEY `es_avaliador_curriculo` (`es_avaliador_curriculo`),
  CONSTRAINT `tb_candidaturas_ibfk_1` FOREIGN KEY (`es_avaliador_competencia1`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_candidaturas_ibfk_2` FOREIGN KEY (`es_candidato`) REFERENCES `tb_candidatos` (`pr_candidato`),
  CONSTRAINT `tb_candidaturas_ibfk_3` FOREIGN KEY (`es_avaliador_competencia1`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_candidaturas_ibfk_6` FOREIGN KEY (`es_avaliador_curriculo`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_candidaturas_ibfk_7` FOREIGN KEY (`es_vaga`) REFERENCES `tb_vagas` (`pr_vaga`),
  CONSTRAINT `tb_candidaturas_ibfk_8` FOREIGN KEY (`es_avaliador_especialista`) REFERENCES `tb_usuarios` (`pr_usuario`)
) ENGINE=InnoDB AUTO_INCREMENT=5773 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_competencias` (
  `pr_competencia` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `vc_competencia` varchar(200) NOT NULL,
  `tx_descrição` text NOT NULL,
  PRIMARY KEY (`pr_competencia`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `tb_configuracao` (
  `co_conf` varchar(30) COLLATE utf8_bin NOT NULL,
  `vc_conf` varchar(255) COLLATE utf8_bin NOT NULL,
  `no_conf` varchar(100) COLLATE utf8_bin NOT NULL,
  `in_ordenacao` int(11) NOT NULL,
  `ch_tipo` char(1) COLLATE utf8_bin NOT NULL DEFAULT 'T',
  `ch_restricao` char(1) COLLATE utf8_bin DEFAULT NULL,
  `in_tamanhomaximo` int(11) NOT NULL,
  PRIMARY KEY (`co_conf`),
  KEY `in_ordenacao` (`in_ordenacao`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_entrevistas` (
  `pr_entrevista` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `es_candidatura` int(10) unsigned NOT NULL,
  `es_avaliador1` int(10) unsigned NOT NULL,
  `es_avaliador2` int(10) unsigned DEFAULT NULL,
  `es_avaliador3` int(10) unsigned DEFAULT NULL,
  `dt_entrevista` datetime NOT NULL,
  `es_alterador` int(10) unsigned NOT NULL,
  `dt_alteracao` date NOT NULL,
  `bl_tipo_entrevista` enum('competencia','especialista') DEFAULT NULL,
  `vc_link` varchar(200) DEFAULT NULL,
  `tx_observacoes` text,
  PRIMARY KEY (`pr_entrevista`),
  UNIQUE KEY `es_candidatura` (`es_candidatura`,`bl_tipo_entrevista`) USING BTREE,
  KEY `es_avaliador1` (`es_avaliador1`),
  KEY `es_avaliador2` (`es_avaliador2`),
  KEY `es_alterador` (`es_alterador`),
  KEY `es_avaliador3` (`es_avaliador3`),
  CONSTRAINT `tb_entrevistas_ibfk_1` FOREIGN KEY (`es_candidatura`) REFERENCES `tb_candidaturas` (`pr_candidatura`),
  CONSTRAINT `tb_entrevistas_ibfk_2` FOREIGN KEY (`es_avaliador1`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_entrevistas_ibfk_3` FOREIGN KEY (`es_avaliador2`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_entrevistas_ibfk_4` FOREIGN KEY (`es_alterador`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_entrevistas_ibfk_5` FOREIGN KEY (`es_avaliador3`) REFERENCES `tb_usuarios` (`pr_usuario`)
) ENGINE=InnoDB AUTO_INCREMENT=325 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `tb_etapas` (
  `pr_etapa` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `vc_etapa` varchar(250) COLLATE utf8_bin NOT NULL,
  `in_ordem` tinyint(3) unsigned DEFAULT NULL,
  `vc_texto` varchar(500) COLLATE utf8_bin DEFAULT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin NOT NULL DEFAULT '0',
  PRIMARY KEY (`pr_etapa`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_experiencias` (
  `pr_experienca` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `es_experiencia_pai` int(11) unsigned DEFAULT NULL,
  `es_candidato` int(10) unsigned NOT NULL,
  `es_candidatura` int(10) unsigned DEFAULT NULL,
  `vc_cargo` varchar(300) COLLATE utf8_bin DEFAULT NULL,
  `vc_empresa` varchar(100) COLLATE utf8_bin NOT NULL,
  `ye_inicio` year(4) DEFAULT NULL,
  `me_inicio` int(2) DEFAULT NULL,
  `dt_inicio` date DEFAULT NULL,
  `ye_fim` year(4) DEFAULT NULL,
  `me_fim` int(2) DEFAULT NULL,
  `dt_fim` date DEFAULT NULL,
  `bl_emprego_atual` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  `tx_atividades` text COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`pr_experienca`),
  KEY `es_experiencia_pai` (`es_experiencia_pai`),
  KEY `es_candidatura` (`es_candidatura`),
  KEY `es_candidato` (`es_candidato`) USING BTREE,
  CONSTRAINT `tb_experiencias_ibfk_1` FOREIGN KEY (`es_candidato`) REFERENCES `tb_candidatos` (`pr_candidato`),
  CONSTRAINT `tb_experiencias_ibfk_2` FOREIGN KEY (`es_experiencia_pai`) REFERENCES `tb_experiencias` (`pr_experienca`),
  CONSTRAINT `tb_experiencias_ibfk_3` FOREIGN KEY (`es_candidatura`) REFERENCES `tb_candidaturas` (`pr_candidatura`)
) ENGINE=InnoDB AUTO_INCREMENT=8410 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_formacao` (
  `pr_formacao` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `es_formacao_pai` int(10) unsigned DEFAULT NULL,
  `es_candidato` int(10) unsigned NOT NULL,
  `es_candidatura` int(10) unsigned DEFAULT NULL,
  `vc_curso` varchar(100) COLLATE utf8_bin NOT NULL,
  `en_tipo` enum('bacharelado','tecnologo','especializacao','mba','mestrado','doutorado','posdoc','seminario') COLLATE utf8_bin NOT NULL,
  `vc_instituicao` varchar(100) COLLATE utf8_bin NOT NULL,
  `ye_conclusao` year(4) DEFAULT NULL,
  `se_conclusao` int(2) DEFAULT NULL,
  `me_conclusao` int(2) DEFAULT NULL,
  `in_cargahoraria` int(10) unsigned DEFAULT NULL,
  `dt_conclusao` date DEFAULT NULL,
  PRIMARY KEY (`pr_formacao`),
  KEY `es_formacao_pai` (`es_formacao_pai`),
  KEY `es_candidatura` (`es_candidatura`),
  KEY `es_candidato` (`es_candidato`) USING BTREE,
  CONSTRAINT `tb_formacao_ibfk_1` FOREIGN KEY (`es_candidato`) REFERENCES `tb_candidatos` (`pr_candidato`),
  CONSTRAINT `tb_formacao_ibfk_2` FOREIGN KEY (`es_formacao_pai`) REFERENCES `tb_formacao` (`pr_formacao`),
  CONSTRAINT `tb_formacao_ibfk_3` FOREIGN KEY (`es_candidatura`) REFERENCES `tb_candidaturas` (`pr_candidatura`)
) ENGINE=InnoDB AUTO_INCREMENT=9024 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_gruposvagas` (
  `pr_grupovaga` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `vc_grupovaga` varchar(250) COLLATE utf8_bin NOT NULL,
  `es_instituicao` int(10) unsigned DEFAULT NULL,
  `es_usuarioCadastro` int(10) unsigned DEFAULT NULL,
  `dt_cadastro` date DEFAULT NULL,
  `es_usuarioAlteracao` int(10) unsigned DEFAULT NULL,
  `dt_alteracao` date DEFAULT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin NOT NULL DEFAULT '0',
  PRIMARY KEY (`pr_grupovaga`),
  KEY `es_usuarioCadastro` (`es_usuarioCadastro`),
  KEY `es_usuarioAlteracao` (`es_usuarioAlteracao`),
  KEY `es_instituicao` (`es_instituicao`),
  CONSTRAINT `tb_gruposvagas_ibfk_1` FOREIGN KEY (`es_usuarioCadastro`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_gruposvagas_ibfk_2` FOREIGN KEY (`es_usuarioAlteracao`) REFERENCES `tb_usuarios` (`pr_usuario`)
) ENGINE=InnoDB AUTO_INCREMENT=84 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_hbdi` (
  `pr_hbdi` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `es_candidatura` int(10) unsigned NOT NULL,
  `dt_hbdi` datetime NOT NULL,
  `bl_motivacao_trabalho1` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho2` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho3` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho4` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho5` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho6` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho7` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho8` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho9` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho10` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho11` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho12` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho13` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho14` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho15` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho16` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho17` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho18` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho19` tinyint(1) DEFAULT NULL,
  `bl_motivacao_trabalho20` tinyint(1) DEFAULT NULL,
  `bl_gosto1` tinyint(1) DEFAULT NULL,
  `bl_gosto2` tinyint(1) DEFAULT NULL,
  `bl_gosto3` tinyint(1) DEFAULT NULL,
  `bl_gosto4` tinyint(1) DEFAULT NULL,
  `bl_gosto5` tinyint(1) DEFAULT NULL,
  `bl_gosto6` tinyint(1) DEFAULT NULL,
  `bl_gosto7` tinyint(1) DEFAULT NULL,
  `bl_gosto8` tinyint(1) DEFAULT NULL,
  `bl_gosto9` tinyint(1) DEFAULT NULL,
  `bl_gosto10` tinyint(1) DEFAULT NULL,
  `bl_gosto11` tinyint(1) DEFAULT NULL,
  `bl_gosto12` tinyint(1) DEFAULT NULL,
  `bl_gosto13` tinyint(1) DEFAULT NULL,
  `bl_gosto14` tinyint(1) DEFAULT NULL,
  `bl_gosto15` tinyint(1) DEFAULT NULL,
  `bl_gosto16` tinyint(1) DEFAULT NULL,
  `bl_gosto17` tinyint(1) DEFAULT NULL,
  `bl_gosto18` tinyint(1) DEFAULT NULL,
  `bl_gosto19` tinyint(1) DEFAULT NULL,
  `bl_gosto20` tinyint(1) DEFAULT NULL,
  `bl_prefiro1` tinyint(1) DEFAULT NULL,
  `bl_prefiro2` tinyint(1) DEFAULT NULL,
  `bl_prefiro3` tinyint(1) DEFAULT NULL,
  `bl_prefiro4` tinyint(1) DEFAULT NULL,
  `bl_prefiro5` tinyint(1) DEFAULT NULL,
  `bl_prefiro6` tinyint(1) DEFAULT NULL,
  `bl_prefiro7` tinyint(1) DEFAULT NULL,
  `bl_prefiro8` tinyint(1) DEFAULT NULL,
  `bl_prefiro9` tinyint(1) DEFAULT NULL,
  `bl_prefiro10` tinyint(1) DEFAULT NULL,
  `bl_prefiro11` tinyint(1) DEFAULT NULL,
  `bl_prefiro12` tinyint(1) DEFAULT NULL,
  `bl_prefiro13` tinyint(1) DEFAULT NULL,
  `bl_prefiro14` tinyint(1) DEFAULT NULL,
  `bl_prefiro15` tinyint(1) DEFAULT NULL,
  `bl_prefiro16` tinyint(1) DEFAULT NULL,
  `bl_prefiro17` tinyint(1) DEFAULT NULL,
  `bl_prefiro18` tinyint(1) DEFAULT NULL,
  `bl_prefiro19` tinyint(1) DEFAULT NULL,
  `bl_prefiro20` tinyint(1) DEFAULT NULL,
  `in_pergunta` int(11) DEFAULT NULL,
  `bl_fazer1` tinyint(1) DEFAULT NULL,
  `bl_fazer2` tinyint(1) DEFAULT NULL,
  `bl_fazer3` tinyint(1) DEFAULT NULL,
  `bl_fazer4` tinyint(1) DEFAULT NULL,
  `bl_fazer5` tinyint(1) DEFAULT NULL,
  `bl_fazer6` tinyint(1) DEFAULT NULL,
  `bl_fazer7` tinyint(1) DEFAULT NULL,
  `bl_fazer8` tinyint(1) DEFAULT NULL,
  `bl_fazer9` tinyint(1) DEFAULT NULL,
  `bl_fazer10` tinyint(1) DEFAULT NULL,
  `bl_fazer11` tinyint(1) DEFAULT NULL,
  `bl_fazer12` tinyint(1) DEFAULT NULL,
  `bl_fazer13` tinyint(1) DEFAULT NULL,
  `bl_fazer14` tinyint(1) DEFAULT NULL,
  `bl_fazer15` tinyint(1) DEFAULT NULL,
  `bl_fazer16` tinyint(1) DEFAULT NULL,
  `bl_comprar1` tinyint(1) DEFAULT NULL,
  `bl_comprar2` tinyint(1) DEFAULT NULL,
  `bl_comprar3` tinyint(1) DEFAULT NULL,
  `bl_comprar4` tinyint(1) DEFAULT NULL,
  `bl_comprar5` tinyint(1) DEFAULT NULL,
  `bl_comprar6` tinyint(1) DEFAULT NULL,
  `bl_comprar7` tinyint(1) DEFAULT NULL,
  `bl_comprar8` tinyint(1) DEFAULT NULL,
  `bl_comprar9` tinyint(1) DEFAULT NULL,
  `bl_comprar10` tinyint(1) DEFAULT NULL,
  `bl_comprar11` tinyint(1) DEFAULT NULL,
  `bl_comprar12` tinyint(1) DEFAULT NULL,
  `bl_comprar13` tinyint(1) DEFAULT NULL,
  `bl_comprar14` tinyint(1) DEFAULT NULL,
  `bl_comprar15` tinyint(1) DEFAULT NULL,
  `bl_comprar16` tinyint(1) DEFAULT NULL,
  `bl_comprar17` tinyint(1) DEFAULT NULL,
  `bl_comprar18` tinyint(1) DEFAULT NULL,
  `bl_comprar19` tinyint(1) DEFAULT NULL,
  `bl_comprar20` tinyint(1) DEFAULT NULL,
  `in_comportamento` int(11) DEFAULT NULL,
  `bl_estilo1` tinyint(1) DEFAULT NULL,
  `bl_estilo2` tinyint(1) DEFAULT NULL,
  `bl_estilo3` tinyint(1) DEFAULT NULL,
  `bl_estilo4` tinyint(1) DEFAULT NULL,
  `bl_estilo5` tinyint(1) DEFAULT NULL,
  `bl_estilo6` tinyint(1) DEFAULT NULL,
  `bl_estilo7` tinyint(1) DEFAULT NULL,
  `bl_estilo8` tinyint(1) DEFAULT NULL,
  `bl_estilo9` tinyint(1) DEFAULT NULL,
  `bl_estilo10` tinyint(1) DEFAULT NULL,
  `bl_estilo11` tinyint(1) DEFAULT NULL,
  `bl_estilo12` tinyint(1) DEFAULT NULL,
  `bl_estilo13` tinyint(1) DEFAULT NULL,
  `bl_estilo14` tinyint(1) DEFAULT NULL,
  `bl_estilo15` tinyint(1) DEFAULT NULL,
  `bl_estilo16` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco1` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco2` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco3` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco4` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco5` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco6` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco7` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco8` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco9` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco10` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco11` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco12` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco13` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco14` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco15` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco16` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco17` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco18` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco19` tinyint(1) DEFAULT NULL,
  `bl_ponto_fraco20` tinyint(1) DEFAULT NULL,
  `in_resolver` int(11) DEFAULT NULL,
  `in_procuro` int(11) DEFAULT NULL,
  `bl_frase1` tinyint(1) DEFAULT NULL,
  `bl_frase2` tinyint(1) DEFAULT NULL,
  `bl_frase3` tinyint(1) DEFAULT NULL,
  `bl_frase4` tinyint(1) DEFAULT NULL,
  `bl_frase5` tinyint(1) DEFAULT NULL,
  `bl_frase6` tinyint(1) DEFAULT NULL,
  `bl_frase7` tinyint(1) DEFAULT NULL,
  `bl_frase8` tinyint(1) DEFAULT NULL,
  `bl_frase9` tinyint(1) DEFAULT NULL,
  `bl_frase10` tinyint(1) DEFAULT NULL,
  `bl_frase11` tinyint(1) DEFAULT NULL,
  `bl_frase12` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`pr_hbdi`),
  UNIQUE KEY `es_candidatura` (`es_candidatura`),
  CONSTRAINT `tb_hbdi_ibfk_1` FOREIGN KEY (`es_candidatura`) REFERENCES `tb_candidaturas` (`pr_candidatura`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `tb_historicocandidaturas` (
  `pr_historico` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `es_candidatura` int(10) unsigned NOT NULL,
  `es_etapa` int(10) unsigned NOT NULL,
  `es_avaliador` int(10) unsigned DEFAULT NULL,
  `dt_avaliacao` datetime NOT NULL,
  `bl_apto` enum('0','1') COLLATE utf8_bin NOT NULL,
  `in_nota` tinyint(3) unsigned DEFAULT NULL,
  `tx_observacao` mediumtext COLLATE utf8_bin,
  `es_usuarioCadastro` int(10) unsigned NOT NULL,
  `dt_cadastro` datetime NOT NULL,
  `es_usuarioAlteracao` int(10) unsigned NOT NULL,
  `dt_alteracao` datetime NOT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin NOT NULL DEFAULT '0',
  PRIMARY KEY (`pr_historico`),
  KEY `IdCandidatura` (`es_candidatura`),
  KEY `IdEtapa` (`es_etapa`),
  KEY `IdAvaliador` (`es_avaliador`),
  KEY `IdUsuarioCadastrador` (`es_usuarioCadastro`),
  KEY `IdUsuarioUltimoAlterador` (`es_usuarioAlteracao`),
  CONSTRAINT `tb_historicocandidaturas_ibfk_1` FOREIGN KEY (`es_candidatura`) REFERENCES `tb_candidaturas` (`pr_candidatura`),
  CONSTRAINT `tb_historicocandidaturas_ibfk_2` FOREIGN KEY (`es_etapa`) REFERENCES `tb_etapas` (`pr_etapa`),
  CONSTRAINT `tb_historicocandidaturas_ibfk_3` FOREIGN KEY (`es_avaliador`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_historicocandidaturas_ibfk_4` FOREIGN KEY (`es_usuarioCadastro`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_historicocandidaturas_ibfk_5` FOREIGN KEY (`es_usuarioAlteracao`) REFERENCES `tb_usuarios` (`pr_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_instituicoes2` (
  `pr_instituicao` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DDNRPESSOAFISJUR` int(10) unsigned DEFAULT NULL,
  `vc_instituicao` varchar(255) NOT NULL,
  `in_tipounidade` int(1) unsigned NOT NULL DEFAULT '0',
  `vc_sigla` varchar(50) NOT NULL,
  `en_sexonome` enum('m','f') DEFAULT NULL,
  `bl_extinto` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`pr_instituicao`),
  UNIQUE KEY `DDNRPESSOAFISJUR` (`DDNRPESSOAFISJUR`)
) ENGINE=InnoDB AUTO_INCREMENT=1260372 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `tb_instituicoes3` (
  `pr_instituicao` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `vc_instituicao` varchar(250) COLLATE utf8_bin NOT NULL,
  `vc_sigla` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `in_codigo` int(10) unsigned DEFAULT NULL,
  `vc_cnpj` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin NOT NULL DEFAULT '0',
  PRIMARY KEY (`pr_instituicao`),
  UNIQUE KEY `in_codigo` (`in_codigo`)
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_log` (
  `pr_log` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `dt_log` datetime NOT NULL,
  `en_tipo` enum('erro','seguranca','sucesso','advertencia') COLLATE utf8_bin NOT NULL,
  `vc_local` varchar(100) COLLATE utf8_bin NOT NULL,
  `es_usuario` int(10) unsigned DEFAULT NULL,
  `vc_tabela` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `in_chave` int(10) unsigned DEFAULT NULL,
  `tx_texto` mediumtext COLLATE utf8_bin NOT NULL,
  `vc_ip` varchar(15) COLLATE utf8_bin NOT NULL,
  `vc_sessao` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`pr_log`),
  KEY `es_usuario` (`es_usuario`) USING BTREE,
  CONSTRAINT `tb_log_ibfk_1` FOREIGN KEY (`es_usuario`) REFERENCES `tb_usuarios` (`pr_usuario`)
) ENGINE=InnoDB AUTO_INCREMENT=332360 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_municipios` (
  `pr_municipio` bigint(20) NOT NULL AUTO_INCREMENT,
  `es_uf` int(10) unsigned NOT NULL,
  `in_codigo` int(10) unsigned NOT NULL,
  `vc_municipio` varchar(250) COLLATE utf8_bin NOT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin NOT NULL DEFAULT '0',
  PRIMARY KEY (`pr_municipio`),
  KEY `es_uf` (`es_uf`),
  CONSTRAINT `tb_municipios_ibfk_1` FOREIGN KEY (`es_uf`) REFERENCES `tb_uf` (`pr_uf`)
) ENGINE=InnoDB AUTO_INCREMENT=5566 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_notas` (
  `pr_nota` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `es_candidatura` int(10) unsigned NOT NULL,
  `in_nota` int(10) unsigned NOT NULL,
  `es_etapa` int(10) unsigned NOT NULL,
  `es_competencia` int(10) unsigned DEFAULT NULL,
  `es_avaliador` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`pr_nota`),
  UNIQUE KEY `es_candidatura_2` (`es_candidatura`,`es_etapa`,`es_competencia`,`es_avaliador`),
  KEY `es_candidatura` (`es_candidatura`),
  KEY `es_etapa` (`es_etapa`),
  KEY `es_competencia` (`es_competencia`),
  KEY `es_avaliador` (`es_avaliador`),
  CONSTRAINT `tb_notas_ibfk_1` FOREIGN KEY (`es_candidatura`) REFERENCES `tb_candidaturas` (`pr_candidatura`),
  CONSTRAINT `tb_notas_ibfk_2` FOREIGN KEY (`es_etapa`) REFERENCES `tb_etapas` (`pr_etapa`),
  CONSTRAINT `tb_notas_ibfk_3` FOREIGN KEY (`es_competencia`) REFERENCES `tb_competencias` (`pr_competencia`),
  CONSTRAINT `tb_notas_ibfk_4` FOREIGN KEY (`es_avaliador`) REFERENCES `tb_usuarios` (`pr_usuario`)
) ENGINE=InnoDB AUTO_INCREMENT=2110 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `tb_opcoes` (
  `pr_opcao` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `es_questao` int(10) unsigned NOT NULL,
  `tx_opcao` mediumtext COLLATE utf8_bin NOT NULL,
  `in_valor` int(10) unsigned DEFAULT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin NOT NULL DEFAULT '0',
  PRIMARY KEY (`pr_opcao`),
  KEY `IDQuestao` (`es_questao`),
  CONSTRAINT `tb_opcoes_ibfk_1` FOREIGN KEY (`es_questao`) REFERENCES `tb_questoes` (`pr_questao`)
) ENGINE=InnoDB AUTO_INCREMENT=6061 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_questoes` (
  `pr_questao` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `es_etapa` int(10) unsigned NOT NULL,
  `tx_questao` mediumtext COLLATE utf8_bin NOT NULL,
  `vc_respostaAceita` varchar(500) COLLATE utf8_bin DEFAULT NULL,
  `in_peso` tinyint(3) unsigned DEFAULT NULL,
  `in_tipo` tinyint(3) unsigned NOT NULL COMMENT '1: Customizadas; 2: Aberta; 3: Sim/Não (Sim positivo); 4: Sim/Não (Não positivo); 5: Nenhum/Básico/Intermediário/Avançado; 6 - Intervalo',
  `bl_eliminatoria` enum('0','1') COLLATE utf8_bin NOT NULL,
  `bl_obrigatorio` enum('0','1') COLLATE utf8_bin NOT NULL,
  `es_usuarioCadastro` int(10) unsigned NOT NULL,
  `dt_cadastro` datetime NOT NULL,
  `es_usuarioAlteracao` int(10) unsigned DEFAULT NULL,
  `dt_alteracao` datetime DEFAULT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin NOT NULL DEFAULT '0',
  `es_competencia` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`pr_questao`),
  KEY `IdEtapa` (`es_etapa`),
  KEY `IdUsuarioCadastrador` (`es_usuarioCadastro`),
  KEY `idUsuarioUltimoAlterador` (`es_usuarioAlteracao`),
  KEY `es_competencia` (`es_competencia`),
  CONSTRAINT `tb_questoes_ibfk_1` FOREIGN KEY (`es_etapa`) REFERENCES `tb_etapas` (`pr_etapa`),
  CONSTRAINT `tb_questoes_ibfk_2` FOREIGN KEY (`es_usuarioCadastro`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_questoes_ibfk_3` FOREIGN KEY (`es_usuarioAlteracao`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_questoes_ibfk_4` FOREIGN KEY (`es_competencia`) REFERENCES `tb_competencias` (`pr_competencia`)
) ENGINE=InnoDB AUTO_INCREMENT=2676 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_respostas` (
  `pr_resposta` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `es_candidatura` int(10) unsigned NOT NULL,
  `es_questao` int(10) unsigned NOT NULL,
  `es_opcao` int(10) unsigned DEFAULT NULL,
  `tx_resposta` longtext COLLATE utf8_bin NOT NULL,
  `dt_resposta` datetime NOT NULL,
  `in_avaliacao` tinyint(3) unsigned DEFAULT NULL,
  `dt_avaliacao` datetime DEFAULT NULL,
  `es_avaliador` int(10) unsigned DEFAULT NULL,
  `es_usuarioCadastro` int(10) unsigned DEFAULT NULL,
  `dt_cadastro` datetime DEFAULT NULL,
  `es_usuarioAlteracao` int(10) unsigned DEFAULT NULL,
  `dt_alteracao` datetime DEFAULT NULL,
  `bl_removido` enum('0','1') COLLATE utf8_bin NOT NULL DEFAULT '0',
  PRIMARY KEY (`pr_resposta`),
  UNIQUE KEY `es_candidatura` (`es_candidatura`,`es_questao`,`es_avaliador`) USING BTREE,
  KEY `IdCandidatura` (`es_candidatura`),
  KEY `IdQuestao` (`es_questao`),
  KEY `IdAvaliador` (`es_avaliador`),
  KEY `IdUsuarioCadastrador` (`es_usuarioCadastro`),
  KEY `IdUsuarioUltimoAlterador` (`es_usuarioAlteracao`),
  KEY `es_opcao` (`es_opcao`),
  CONSTRAINT `tb_respostas_ibfk_1` FOREIGN KEY (`es_candidatura`) REFERENCES `tb_candidaturas` (`pr_candidatura`),
  CONSTRAINT `tb_respostas_ibfk_2` FOREIGN KEY (`es_questao`) REFERENCES `tb_questoes` (`pr_questao`),
  CONSTRAINT `tb_respostas_ibfk_3` FOREIGN KEY (`es_avaliador`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_respostas_ibfk_4` FOREIGN KEY (`es_usuarioCadastro`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_respostas_ibfk_5` FOREIGN KEY (`es_usuarioAlteracao`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_respostas_ibfk_6` FOREIGN KEY (`es_opcao`) REFERENCES `tb_opcoes` (`pr_opcao`)
) ENGINE=InnoDB AUTO_INCREMENT=83140 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE IF NOT EXISTS `tb_sessoes` (
  `id` varchar(128) COLLATE utf8_bin NOT NULL,
  `ip_address` varchar(45) COLLATE utf8_bin NOT NULL,
  `timestamp` int(10) unsigned NOT NULL DEFAULT '0',
  `data` blob NOT NULL,
  `es_usuario` int(10) unsigned DEFAULT NULL,
  KEY `ci_sessions_timestamp` (`timestamp`),
  KEY `es_usuario` (`es_usuario`),
  CONSTRAINT `tb_sessoes_ibfk_1` FOREIGN KEY (`es_usuario`) REFERENCES `tb_usuarios` (`pr_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_status_candidaturas` (
  `pr_status` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `in_status_legado` tinyint(3) unsigned DEFAULT NULL,
  `vc_status` varchar(50) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`pr_status`),
  UNIQUE KEY `in_status_legado` (`in_status_legado`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_uf` (
  `pr_uf` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ch_sigla` char(2) COLLATE utf8_bin NOT NULL,
  `vc_uf` varchar(20) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`pr_uf`),
  UNIQUE KEY `ds_sigla` (`ch_sigla`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_usuarios` (
  `pr_usuario` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `es_candidato` int(10) unsigned DEFAULT NULL,
  `en_perfil` enum('candidato','avaliador','sugesp','orgaos','administrador') COLLATE utf8_bin NOT NULL,
  `vc_nome` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `vc_email` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `vc_telefone` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `vc_login` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `vc_senha` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `vc_senha_temporaria` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `dt_cadastro` date DEFAULT NULL,
  `dt_alteracao` date DEFAULT NULL,
  `dt_ultimoacesso` datetime DEFAULT NULL,
  `bl_trocasenha` enum('0','1') COLLATE utf8_bin DEFAULT '1',
  `in_erros` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `bl_removido` enum('0','1') COLLATE utf8_bin DEFAULT '0',
  PRIMARY KEY (`pr_usuario`),
  KEY `IdCandidato` (`es_candidato`)
) ENGINE=InnoDB AUTO_INCREMENT=6033 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `tb_vagas` (
  `pr_vaga` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `vc_vaga` varchar(250) CHARACTER SET utf8 NOT NULL,
  `tx_descricao` text CHARACTER SET utf8,
  `dt_inicio` datetime DEFAULT NULL,
  `dt_fim` datetime DEFAULT NULL,
  `vc_linkEntrevista` varchar(300) CHARACTER SET utf8 DEFAULT NULL,
  `in_statusVaga` tinyint(3) unsigned NOT NULL,
  `es_instituicao` int(10) unsigned DEFAULT NULL,
  `es_instituicao2` int(10) unsigned DEFAULT NULL,
  `es_grupoVaga` int(10) unsigned DEFAULT NULL,
  `es_usuarioCadastro` int(10) unsigned NOT NULL,
  `dt_cadastro` datetime NOT NULL,
  `es_usuarioAlteracao` int(10) unsigned DEFAULT NULL,
  `dt_alteracao` datetime DEFAULT NULL,
  `bl_removido` enum('0','1') CHARACTER SET utf8 NOT NULL DEFAULT '0',
  `bl_liberado` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  `bl_brumadinho` tinyint(1) DEFAULT NULL,
  `bl_finalizado` enum('0','1') COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`pr_vaga`),
  KEY `IdOrgao` (`es_instituicao2`),
  KEY `IdGrupoVaga` (`es_grupoVaga`),
  KEY `es_usuarioCadastro` (`es_usuarioCadastro`),
  KEY `es_usuarioAlteracao` (`es_usuarioAlteracao`),
  KEY `es_instituicao` (`es_instituicao`),
  CONSTRAINT `tb_vagas_ibfk_1` FOREIGN KEY (`es_instituicao2`) REFERENCES `tb_instituicoes3` (`pr_instituicao`),
  CONSTRAINT `tb_vagas_ibfk_2` FOREIGN KEY (`es_grupoVaga`) REFERENCES `tb_gruposvagas` (`pr_grupovaga`),
  CONSTRAINT `tb_vagas_ibfk_3` FOREIGN KEY (`es_usuarioCadastro`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_vagas_ibfk_4` FOREIGN KEY (`es_usuarioAlteracao`) REFERENCES `tb_usuarios` (`pr_usuario`),
  CONSTRAINT `tb_vagas_ibfk_5` FOREIGN KEY (`es_instituicao`) REFERENCES `tb_instituicoes2` (`pr_instituicao`)
) ENGINE=InnoDB AUTO_INCREMENT=164 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
