version: "3.3"

services:
  server:
    image: 127.0.0.1:5000/transforma_stack  #the address of the registry
    ports:
      - "8080:80"
    volumes:
      - ./:/transformagov/
      - anexos:/transformagov/anexos
    env_file:
      - .env.prod
    environment:
      - DB_HOST=transforma_stack_db
      - DB_DATABASE=transforma
      - DB_PASSWORD=root
      - DB_USERNAME=root
    networks:
      - nginx_server
  db:
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transforma
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - nginx_server
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      #- letsencrypt:/etc/letsencrypt
      - ./docker/prod/transforma.conf:/etc/nginx/conf.d/default.conf
      - ./:/transformagov/
    networks:
      - nginx_server


volumes:
  transforma-db:
  #letsencrypt:
  anexos:

networks:
  nginx_server: