version: "3.3"

services:
  server:
    build:
      context: ./
    ports:
      - "8085:8085"
    volumes:
      - ./:/transformagov/
    entrypoint: ["php", "spark", "serve", "--host", "0.0.0.0", "--port", "8085"]
    environment:
      - DB_HOST=db
      - DB_DATABASE=transforma
      - DB_PASSWORD=root
      - DB_USERNAME=root
      - CI_DEBUG=true
      - CI_ENVIRONMENT=development
  db:
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transforma
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
volumes:
  transforma-db:
