version: "3.3"

services:
  server:
    build:
      context: ./
      dockerfile: docker/local/Dockerfile
    ports:
      - "$PORT:80"
    volumes:
      - ./:/transformagov/
      - anexos:/transformagov/anexos
    env_file:
      - .env
    networks:
      - nginx_server
    
  db:
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transforma
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - nginx_server
  nginx:
    image: nginx:latest
    container_name: transformagov_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/local/transforma.conf:/etc/nginx/conf.d/default.conf
      - ./:/transformagov/
    networks:
      - nginx_server
volumes:
  transforma-db:
  anexos:

networks:
  nginx_server: