version: "3.3"

services:
  server:
    build:
      context: ./
      dockerfile: docker/local/Dockerfile
    ports:
      - "$PORT:80"
    volumes:
      - ./:/transformagov/
    env_file:
      - .env
    entrypoint: /tmp/run.sh
    
  db:
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transforma
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
volumes:
  transforma-db:
