version: "3.3"

services:
  server:
    image: 127.0.0.1:5000/transforma_stack  #the address of the registry
    build:
      context: ./
    ports:
      - "8080:80"
    volumes:
      - ./:/transformagov/
    env_file:
      - .env
    entrypoint: /tmp/run.sh
    environment:
      - DB_HOST=transformagov_db_1
      - DB_DATABASE=transforma
      - DB_PASSWORD=root
      - DB_USERNAME=root
  db:
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transforma
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
volumes:
  transforma-db:
