version: "3.3"

services:
  server:
    build:
      context: ./
    ports:
      - "8080:80"
    volumes:
      - ./:/transformagov/
    env_file:
      - .env
    entrypoint: /tmp/run.sh
    environment:
      - DB_HOST=transformagov_db_1
      - DB_DATABASE=transforma
      - DB_PASSWORD=root
      - DB_USERNAME=root
  db:
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transforma
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo

  cypress-cli:
    image: cypress/included:9.0.0
    container_name: cypress-cli
    working_dir: /cypress
    volumes:
      - ./application/cypress/cypress.json:/cypress/cypress.json
      - ./application/cypress/integration:/cypress/cypress/integration
    depends_on:
      - server
    ports:
      - 8005:8005

  cypress-gui:
    image: cypress/included:9.0.0
    container_name: cypress-gui
    working_dir: /cypress
    volumes:
      - ./application/cypress/cypress.json:/cypress/cypress.json
      - ./application/cypress/integration:/cypress/cypress/integration
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
    depends_on:
      - server
    ports:
      - 8005:8005
    entrypoint: ["npx", "cypress", "open", "-P", "/cypress"]
volumes:
  transforma-db:
