version: "3.3"

services:
  server:
    build:
      context: ./
      dockerfile: docker/local/Dockerfile
    ports:
      - "$PORT:80"
    volumes:
      - ./:/transformagov/
      - anexos:/transformagov/anexos
    entrypoint: /tmp/run.sh
    env_file:
      - .env
    
  db:
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transforma
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
  nginx:
    build:
      context: ./
      dockerfile: docker/local/Dockerfile-nginx
    container_name: transformagov_nginx
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - ./docker/local/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  transforma-db:
  anexos:
