version: "3.3"

services:
  server:
    image: 127.0.0.1:5000/transformagovrj_local_server
    ports:
      - "8081:80"
    volumes:
      - anexos:/transformagov/anexos
    env_file:
      - .env.local-swarm
    entrypoint: /tmp/run.sh
    environment:
      - DB_HOST=transformagovrj_local_db
      - DB_DATABASE=transforma
      - DB_PASSWORD=root
      - DB_USERNAME=root
  db:
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transforma
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo

volumes:
  transforma-db:
  anexos:

