version: "3.4"

x-swarm-common: &swarm-common
  networks:
    - public

services:
  server:
    <<: *swarm-common
    image: ${registry}/transforma_server:bootstrap-sb-admin-2-prod
    entrypoint: /tmp/run.sh
    env_file:
      - production/transforma/stacks/server-variables.env
  db:
    <<: *swarm-common
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    env_file:
      - production/transforma/stacks/db-variables.env
volumes:
  transforma-db:
networks:
  public:
    external:
      name: "nginx_prod_public"
