version: "3.4"

x-swarm-common: &swarm-common
  networks:
    - public

services:
  server:
    <<: *swarm-common
    image: ${registry}/transforma_server:bootstrap-sb-admin-2-prod
    entrypoint: /tmp/run.sh
    environment:
      - ENV_NAME_PLATFORM="Transforma Minas"
      - ENV_SUB_TITLE_PLATFORM=""
      - ENV_SMTP_HOST='smtp.mailgun.org'
      - ENV_SMTP_PORT=587
      - ENV_SMTP_USER='transformaminas@pencillabs.com.br'
      - ENV_SMTP_PASS='2d657985dbf03eb123040b63bcfb255f-28d78af2-3dbbfc4c'
      - ENV_CONTACT_EMAIL=''
      - ENV_ADMIN_EMAIL=''
  db:
    <<: *swarm-common
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transforma
      - MYSQL_ROOT_PASSWORD=root
volumes:
  transforma-db:
networks:
  public:
    external:
      name: "nginx_prod_public"
