version: "3.4"

x-swarm-common: &swarm-common
  networks:
    - public

services:
  server:
    <<: *swarm-common
    image: ${registry}/transforma_server:adicoes-email-prod2
    entrypoint: /tmp/run.sh
    environment:
      - ENV_NAME_PLATFORM="Transforma Minas"
      - ENV_SUB_TITLE_PLATFORM="Transforma Minas"
      - ENV_SMTP_HOST=smtp.mailgun.org
      - ENV_SMTP_PORT=587
      - ENV_SMTP_USER=transformaminas@pencillabs.com.br
      - ENV_SMTP_PASS=63a6c465a40194ad142b45cfdf09f26d-64574a68-0345dbcf
      - ENV_PROTOCOL=smtp
      - ENV_SMTP_AUTH=TRUE
      - ENV_SMTP_CRYPTO=tls
      - ENV_CONTACT_EMAIL=''
      - ENV_ADMIN_EMAIL=''
      - ENV_CHARSET=UTF-8
      - ENV_WORDWRAP=TRUE
      - ENV_MAILTYPE=html
      - ENV_CONTACT_EMAIL=transformaminas@pencillabs.com.br
      - ENV_ADMIN_EMAIL=transformaminas@pencillabs.com.br
      - TZ=America/Sao_Paulo
  db:
    <<: *swarm-common
    image: mariadb:10.3
    volumes:
      - transforma-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transforma
      - MYSQL_ROOT_PASSWORD=root
volumes:
  transforma-db:
networks:
  public:
    external:
      name: "nginx_prod_public"
